services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev", "--host", "0.0.0.0"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ex-dev-http.rule=Host(`ex.surfingbird.space`)"
      - "traefik.http.routers.ex-dev-http.entrypoints=web"
      - "traefik.http.routers.ex-dev-http.middlewares=redirect-to-https-ex-dev"
      - "traefik.http.routers.ex-dev.rule=Host(`ex.surfingbird.space`)"
      - "traefik.http.routers.ex-dev.entrypoints=websecure"
      - "traefik.http.routers.ex-dev.tls=true"
      - "traefik.http.routers.ex-dev.tls.certresolver=myresolver"
      - "traefik.http.services.ex-dev.loadbalancer.server.port=5173"
      - "traefik.http.middlewares.redirect-to-https-ex-dev.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https-ex-dev.redirectscheme.permanent=true"
    networks:
      - service_network

networks:
  service_network:
    external: true
